import Head from 'next/head';

import AppNavBar from '../components/AppNavBar';
import AppBulletList from '../components/AppBulletList';

const itens = {
  date: '06/10/2021',
  data: [
    {
      id: 1,
      type: 'task',
      title: 'Codificar o componente bullte list',
    },
    {
      id: 2,
      type: 'task',
      title: 'Codificar o componente bullte list',
    },
    {
      id: 3,
      type: 'event',
      title: '8h30 Momento síncrono de Prog Orientada a serviços',
    },
    {
      id: 4,
      type: 'note',
      title: 'Lembrar de falar sobre key nas listas',
    },
    {
      id: 5,
      type: 'note',
      title: 'Lembrar de falar sobre lista e mapas',
    },
  ],
};

export default function Home () {
  let title = 'Meu Bullet Journal';

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppNavBar title={title} />
      <AppBulletList date={itens.date} bullets={itens.data} />
    </div>
  );
}
