import Head from 'next/head';

import AppNavBar from '../components/AppNavBar';
import AppBulletList from '../components/AppBulletList';

export default function Home () {
  let title = 'Meu Bullet Journal';

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppNavBar title={title} />
      <AppBulletList title="29/09/2021" />
      <AppBulletList title="30/09/2021" />
      <AppBulletList title="01/10/2021" />
    </div>
  );
}
