import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home () {
  // jsx

  let title = 'Meu Primeiro Web App';

  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {title}
        </h1>
        <h2>Minhas tarefas diárias</h2>
        <h2>Ramificação nova (branch)</h2>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          Infoweb 2021
        </a>
      </footer>
    </div>
  );
}
